name: Run PHP Script

on:
  schedule:
    - cron: ' 0 0 */3 * *'  # 每三天午夜运行
  workflow_dispatch:  # 也可以手动触发

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # 根据需要选择 PHP 版本

      - name: Install dependencies
        run: composer install
        working-directory: ./  # 确保这是你的项目根目录

      - name: Run PHP Script and capture output
        run: php lanzouyunapi.php > output.json
        working-directory: ./  # 确保这是你的项目根目录
        env:
          REDIRECT: false  # 设置环境变量，根据需要调整
          TYPES: json      # 设置返回类型为 JSON

      - name: Check output file content
        run: cat output.json
        working-directory: ./  # 确保这是你的项目根目录

      - name: Commit and push output file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output.json
          git commit -m "Update output file" || echo "No changes to commit"
          git push origin HEAD
